### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by merc1er** [unisat-wallet/libbrc20-indexer#2]
Are there any plans on adding documentation? Or is it hosted somewhere outside the repo?

**Comment by andredevjs** [comment]
So far this is not an actual indexer, it mostly parses and input, applies the brc20 standard and generates the output with it.

This sample uses [data/brc20input.txt](https://github.com/unisat-wallet/libbrc20-indexer/blob/main/data/brc20.input.txt) (block height 783025 -2023-03-09 19:19:43 UTC)

And generates and brc20output.txt.

There is no instructions of how to generate the input file, but if you look at: https://github.com/unisat-wallet/libbrc20-indexer/blob/main/loader/loader.go
That's the structure it needs.

**Comment by merc1er** [comment]
Ah I see.

Would you know of an indexer for BRC 20 tokens? For example, what does unisat use to index transactions/tokens?

**Comment by andredevjs** [comment]
prob an ord server, with a custom script to export data like that.
I would say an easy implementation will be to query /inscriptions, filter brc20 inscriptions, and use that data to generate the input.
I'll work on it next Monday, I can share the solution.

**Comment by crackxia** [comment]
> prob an ord server, with a custom script to export data like that. I would say an easy implementation will be to query /inscriptions, filter brc20 inscriptions, and use that data to generate the input. I'll work on it next Monday, I can share the solution.

Hello, how to generate brc20input.txt？
