### ISSUE TITLE
What does CreateIdxKey do?

### ISSUE THREAD

**Issue by tiangong3624749** [unisat-wallet/libbrc20-indexer#3]
When loading input data, I found CreateIdxKey property.
and i want to know What does CreateIdxKey do in ordinals protocol?

**Comment by tiangong3624749** [comment]
i got it, thanks.

**Comment by Ljzn** [comment]
Hello @tiangong3624749 , I'm looking into CreateIdxKey too. Could you tell me what is it? And how to get it? Thanks!
